#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

sudo pkg update &&
    sudo pkg install -y python ca_root_nss &&
    sudo pkg clean -y &&
    sudo python -m ensurepip &&
    sudo pip install --upgrade pip
